/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculadora_java;

public class App {
   

    public static void main(String[] args) {
        Calculadora cal = new Calculadora();
        System.out.println(cal.somar(5, 6));
         System.out.println(cal.dividir(2, 2));
          System.out.println(cal.subtrair(5, 3));
           System.out.println(cal.multiplicar(2, 2));
    }
     
}
